#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# mkdir -p \
#     /app/netbox/netbox/static \
#     /config/scripts

if [[ -f "/etc/weewx/weewx.conf" ]]; then
    exit 0
fi

cp -a /etc/dist-weewx/. /etc/weewx/
