name: "Docker LSB Test"

on:
  push:
    branches:
      - 'linuxserver-s6'

jobs:
  docker:
    name: "Docker"
    uses: dosquad/actions/.github/workflows/docker-release.yml@main
    with:
      image: ghcr.io/dosquad/weewx
      platforms: 'linux/amd64,linux/arm64'
      manual-tag: 'linuxserver-s6'
    secrets: inherit
