name: "Docker Release"

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  docker:
    name: "Docker"
    uses: dosquad/actions/.github/workflows/docker-release.yml@main
    with:
      image: ghcr.io/dosquad/weewx
      platforms: 'linux/amd64,linux/arm64'
      latest-on-branch: '{{is_default_branch}}'
    secrets: inherit
